name: media_kit
description: A cross-platform video player & audio player for Flutter & Dart. Performant, stable, feature-proof & modular.
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  http: ">=0.13.0 <2.0.0"
  image: ^4.0.17
  js: ^0.7.1
  meta: ^1.8.0
  path: ^1.8.0
  safe_local_storage: ^2.0.1
  synchronized: ^3.1.0
  universal_platform: ^1.0.0+1
  web: ^1.1.0
  uri_parser: ^3.0.0
  uuid: ">=2.0.0 <5.0.0"

dev_dependencies:
  test: ^1.24.1
  lints: ^5.0.0

ffigen:
  name: MPV
  output: bin/generated/libmpv/bindings.dart
  headers:
    entry-points:
      - headers/client.h
  dart-bool: true

flutter:
  assets:
    - assets/web/
